import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  getData() {
    return {
      'algs': [{
        'name': 'Тест Соловэя-Штрассена',
        'cases': [{
          'numbers': 1000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 8,
            'error': 0.02649007,
            'timeMillis': 4,
            'expectedTime': 26,
            'difference': 22
          }, {
            'iterations': 2,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2,
            'expectedTime': 53,
            'difference': 51
          }, {
            'iterations': 3,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 80,
            'difference': 79
          }, {
            'iterations': 4,
            'pseudoPrimes': 1,
            'error': 0.00331126,
            'timeMillis': 2,
            'expectedTime': 107,
            'difference': 105
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 134,
            'difference': 133
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 161,
            'difference': 160
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2,
            'expectedTime': 188,
            'difference': 186
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 215,
            'difference': 214
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2,
            'expectedTime': 242,
            'difference': 240
          }],
          'primes': 302
        }, {
          'numbers': 10000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 27,
            'error': 0.0119469,
            'timeMillis': 8,
            'expectedTime': 64,
            'difference': 56
          }, {
            'iterations': 2,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 9,
            'expectedTime': 128,
            'difference': 119
          }, {
            'iterations': 3,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 17,
            'expectedTime': 192,
            'difference': 175
          }, {
            'iterations': 4,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 12,
            'expectedTime': 256,
            'difference': 244
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 12,
            'expectedTime': 320,
            'difference': 308
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 14,
            'expectedTime': 384,
            'difference': 370
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 14,
            'expectedTime': 448,
            'difference': 434
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 14,
            'expectedTime': 512,
            'difference': 498
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 19,
            'expectedTime': 576,
            'difference': 557
          }],
          'primes': 2260
        }, {
          'numbers': 100000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 64,
            'error': 0.00355892,
            'timeMillis': 125,
            'expectedTime': 125,
            'difference': 0
          }, {
            'iterations': 2,
            'pseudoPrimes': 6,
            'error': 3.3365E-4,
            'timeMillis': 150,
            'expectedTime': 250,
            'difference': 100
          }, {
            'iterations': 3,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 136,
            'expectedTime': 375,
            'difference': 239
          }, {
            'iterations': 4,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 136,
            'expectedTime': 500,
            'difference': 364
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 145,
            'expectedTime': 625,
            'difference': 480
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 153,
            'expectedTime': 750,
            'difference': 597
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 163,
            'expectedTime': 875,
            'difference': 712
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 174,
            'expectedTime': 1000,
            'difference': 826
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 183,
            'expectedTime': 1125,
            'difference': 942
          }],
          'primes': 17983
        }, {
          'numbers': 1000000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 219,
            'error': 0.00147047,
            'timeMillis': 2000,
            'expectedTime': 215,
            'difference': -1784
          }, {
            'iterations': 2,
            'pseudoPrimes': 6,
            'error': 4.029E-5,
            'timeMillis': 2102,
            'expectedTime': 431,
            'difference': -1670
          }, {
            'iterations': 3,
            'pseudoPrimes': 2,
            'error': 1.343E-5,
            'timeMillis': 2200,
            'expectedTime': 647,
            'difference': -1552
          }, {
            'iterations': 4,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2265,
            'expectedTime': 863,
            'difference': -1401
          }, {
            'iterations': 5,
            'pseudoPrimes': 1,
            'error': 6.71E-6,
            'timeMillis': 2377,
            'expectedTime': 1079,
            'difference': -1297
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2452,
            'expectedTime': 1295,
            'difference': -1156
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2567,
            'expectedTime': 1511,
            'difference': -1055
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2649,
            'expectedTime': 1727,
            'difference': -921
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2739,
            'expectedTime': 1943,
            'difference': -795
          }],
          'primes': 148932
        }, {
          'numbers': 10000000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 519,
            'error': 4.0847E-4,
            'timeMillis': 48302,
            'expectedTime': 343,
            'difference': -47959
          }, {
            'iterations': 2,
            'pseudoPrimes': 33,
            'error': 2.597E-5,
            'timeMillis': 46058,
            'expectedTime': 686,
            'difference': -45372
          }, {
            'iterations': 3,
            'pseudoPrimes': 10,
            'error': 7.87E-6,
            'timeMillis': 47766,
            'expectedTime': 1029,
            'difference': -46737
          }, {
            'iterations': 4,
            'pseudoPrimes': 2,
            'error': 1.57E-6,
            'timeMillis': 47914,
            'expectedTime': 1372,
            'difference': -46542
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 49627,
            'expectedTime': 1715,
            'difference': -47912
          }, {
            'iterations': 6,
            'pseudoPrimes': 2,
            'error': 1.57E-6,
            'timeMillis': 49769,
            'expectedTime': 2058,
            'difference': -47711
          }, {
            'iterations': 7,
            'pseudoPrimes': 1,
            'error': 7.9E-7,
            'timeMillis': 50187,
            'expectedTime': 2401,
            'difference': -47786
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 51249,
            'expectedTime': 2744,
            'difference': -48505
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 52640,
            'expectedTime': 3087,
            'difference': -49553
          }],
          'primes': 1270606
        }]
      }, {
        'name': 'Тест Миллера-Рабина',
        'cases': [{
          'numbers': 1000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 5,
            'error': 0.01655629,
            'timeMillis': 2,
            'expectedTime': 26,
            'difference': 24
          }, {
            'iterations': 2,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 0,
            'expectedTime': 53,
            'difference': 53
          }, {
            'iterations': 3,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 0,
            'expectedTime': 80,
            'difference': 80
          }, {
            'iterations': 4,
            'pseudoPrimes': 1,
            'error': 0.00331126,
            'timeMillis': 1,
            'expectedTime': 107,
            'difference': 106
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2,
            'expectedTime': 134,
            'difference': 132
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 161,
            'difference': 160
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 188,
            'difference': 187
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 215,
            'difference': 214
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1,
            'expectedTime': 242,
            'difference': 241
          }],
          'primes': 302
        }, {
          'numbers': 10000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 14,
            'error': 0.00619469,
            'timeMillis': 6,
            'expectedTime': 64,
            'difference': 58
          }, {
            'iterations': 2,
            'pseudoPrimes': 4,
            'error': 0.00176991,
            'timeMillis': 7,
            'expectedTime': 128,
            'difference': 121
          }, {
            'iterations': 3,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 41,
            'expectedTime': 192,
            'difference': 151
          }, {
            'iterations': 4,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 7,
            'expectedTime': 256,
            'difference': 249
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 10,
            'expectedTime': 320,
            'difference': 310
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 8,
            'expectedTime': 384,
            'difference': 376
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 12,
            'expectedTime': 448,
            'difference': 436
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 8,
            'expectedTime': 512,
            'difference': 504
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 10,
            'expectedTime': 576,
            'difference': 566
          }],
          'primes': 2260
        }, {
          'numbers': 100000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 56,
            'error': 0.00311405,
            'timeMillis': 85,
            'expectedTime': 125,
            'difference': 40
          }, {
            'iterations': 2,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 108,
            'expectedTime': 250,
            'difference': 142
          }, {
            'iterations': 3,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 95,
            'expectedTime': 375,
            'difference': 280
          }, {
            'iterations': 4,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 142,
            'expectedTime': 500,
            'difference': 358
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 111,
            'expectedTime': 625,
            'difference': 514
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 112,
            'expectedTime': 750,
            'difference': 638
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 144,
            'expectedTime': 875,
            'difference': 731
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 124,
            'expectedTime': 1000,
            'difference': 876
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 129,
            'expectedTime': 1125,
            'difference': 996
          }],
          'primes': 17983
        }, {
          'numbers': 1000000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 126,
            'error': 8.4602E-4,
            'timeMillis': 1793,
            'expectedTime': 215,
            'difference': -1577
          }, {
            'iterations': 2,
            'pseudoPrimes': 6,
            'error': 4.029E-5,
            'timeMillis': 1879,
            'expectedTime': 431,
            'difference': -1447
          }, {
            'iterations': 3,
            'pseudoPrimes': 1,
            'error': 6.71E-6,
            'timeMillis': 1836,
            'expectedTime': 647,
            'difference': -1188
          }, {
            'iterations': 4,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1890,
            'expectedTime': 863,
            'difference': -1026
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1936,
            'expectedTime': 1079,
            'difference': -856
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 1981,
            'expectedTime': 1295,
            'difference': -685
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2039,
            'expectedTime': 1511,
            'difference': -527
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2169,
            'expectedTime': 1727,
            'difference': -441
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 2511,
            'expectedTime': 1943,
            'difference': -567
          }],
          'primes': 148932
        }, {
          'numbers': 10000000,
          'cases': [{
            'iterations': 1,
            'pseudoPrimes': 311,
            'error': 2.4477E-4,
            'timeMillis': 41319,
            'expectedTime': 343,
            'difference': -40976
          }, {
            'iterations': 2,
            'pseudoPrimes': 9,
            'error': 7.08E-6,
            'timeMillis': 46891,
            'expectedTime': 686,
            'difference': -46205
          }, {
            'iterations': 3,
            'pseudoPrimes': 1,
            'error': 7.9E-7,
            'timeMillis': 42983,
            'expectedTime': 1029,
            'difference': -41954
          }, {
            'iterations': 4,
            'pseudoPrimes': 2,
            'error': 1.57E-6,
            'timeMillis': 43110,
            'expectedTime': 1372,
            'difference': -41738
          }, {
            'iterations': 5,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 42842,
            'expectedTime': 1715,
            'difference': -41127
          }, {
            'iterations': 6,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 43093,
            'expectedTime': 2058,
            'difference': -41035
          }, {
            'iterations': 7,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 43879,
            'expectedTime': 2401,
            'difference': -41478
          }, {
            'iterations': 8,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 44810,
            'expectedTime': 2744,
            'difference': -42066
          }, {
            'iterations': 9,
            'pseudoPrimes': 0,
            'error': 0.0,
            'timeMillis': 44608,
            'expectedTime': 3087,
            'difference': -41521
          }],
          'primes': 1270606
        }]
      }]
    };
  }

  total() {
    return Array(35);
  }

  rowSpan() {
    return this.getData().algs[0].cases.length * this.getData().algs[0].cases[0].cases.length;
  }

  getFirst() {
    return this.getData().algs[0];
  }

  getSecond() {
    return this.getData().algs[1];
  }

}
